### ISSUE TITLE
MuseScore piano-tutor lighting wrong keys

### ISSUE THREAD

**Issue by Paffo** [tomcucinotta/MuseScore#1]
Hello,
Im running Ubuntu 18.04, i compiled the latest musescore piano tutor from here, and it starts without a problem, it detects the arduino, and sends it keys.
The problem is that not only Left and Right hands are backwards, but the keys are completely wrong.
Thinking it was an arduino problem i tried sending them manually via serial, but the correct keys light up.
I tried the "wizard" but it only messes it up even more.
My Strip is 88 leds, 1 for each key of my piano.
With synthesia and my arduino code that emulates MIDI it works fine, but synthesia doesnt have "look ahead" function, which im looking for really hard.

**Comment by tomcucinotta** [comment]
Hi, my best guess is that your LED stripe is positioned reversed, w.r.t. what I've been testing it with. Normally, I have my Arduino on the right of the piano, there it attaches to the LED stripe, that is laid down from right to left, so I have the "LEDs backward option CHECKED". In this set-up, LED n.0 is the rightmost, then we move from right to left, as the LED number increases. This can be checked directly from the Arduino Serial Monitor, sending the manual key codes as explained in the tutorial.
Now, as per theory, the system should support LEDs laid down from left to right as well, in such case you'd have to UNCHECK the "LEDs backward" option, albeit I have to confess I can barely remember to have made any kind of testing under these conditions (if I ever did any ;-P).
The Wizard is probably not very intelligent at the moment, so I'd recommend NOT to use it.

If you have a 88-LED stripe (btw, where did you get it from?) then you'd need to set the LEDs per key dropdown to 1 (the default of 2, corresponds to my set-up with a 144 LEDs/meter stripe, which has 2 LEDs per key), with either the backward checkbox checked (if Arduino on right, LEDs towards left), or unchecked (if Arduino on your left, LEDs advancing towards right).

I hope this helps, please, let me know what else happens.

Thanks.

**Comment by Paffo** [comment]
Hello,
i cant belive i spent 4 hours looking for a problem solvable by unchecking...
is there a way i can change the color other then the brightness of the "incoming" notes?
Like having the to-press in green but the incoming in white for instance.
Anyway, i've bult the 88 strip myself with cablecase and the 144/m strips.
i spent about 2-3 hours to assembly it all, and its very convenient.
here are some pictures 
https://i.imgur.com/SwO9Xse.jpg
https://i.imgur.com/U4q8CGr.jpg
https://i.imgur.com/SkASfJ4.jpg
https://i.imgur.com/iJpBbNx.jpg
https://i.imgur.com/iJpBbNx.jpg

**Comment by tomcucinotta** [comment]
Hi, your LED assembly looks really cool, thanks for sharing the pics :)!
As for the colors, I have only the two major left and right hand colors
customizable, then for incoming keys I just use those colors divided by 2
(if memory serves). You can change that behavior by editing the MuseScore
sources, in the tutor.cpp file.

Il lun 8 ott 2018, 22:57 Paffo <notifications@github.com> ha scritto:

**Comment by Paffo** [comment]
Despite i'm just a C# and JS programmer i'll try, thanks to the answers and the overall help,
will let you know

**Comment by tomcucinotta** [comment]
I created a new follow-up issue (#2) for the upcoming keys customization
https://github.com/tomcucinotta/MuseScore/issues/2

So, I'm closing this one.
