### ISSUE TITLE
Miscellanious LED questions

### ISSUE THREAD

**Issue by joshaguilera** [tomcucinotta/MuseScore#13]
Will it matter if I do not use the same brand of programmable LED’s? Also I will be soldering an extra bit as to fill up my entire keyboard, so do you have any recommendations on editing your code? :)﻿

**Comment by tomcucinotta** [comment]
The Arduino .ino file has a NUMPIXELS constant controlling how many LEDs you have on your stripe. In case of longer stripes, that number has to be accordingly increased.
```
  // How many NeoPixels are attached to the Arduino?
  #define NUMPIXELS      144
```
I wouldn't expect any needed change to the way LEDs are driven, if you manage to solder the 2nd stripe keeping exactly the same LED distance distribution, from the last LED of one stripe to the 1st LED on the other, as across the first stripe.
In case you use a different stripe that uses a different clock, and/or RGB scheme, but it keeps being compatible with the NeoPixel library, then you need to change the corresponding line:
```
// When we setup the NeoPixel library, we tell it how many pixels, and which pin to use to send signals.
// Note that for older NeoPixel strips you might need to change the third parameter--see the strandtest
// example for more information on possible values.
Adafruit_NeoPixel pixels = Adafruit_NeoPixel(NUMPIXELS, PIN, NEO_GRB + NEO_KHZ800);
```
I hope you'd have some technical spec for the stripe you plan to use, with such details. Your best friend might be the documentation of the NeoPixel library, and list of supported devices (if any), but I'm not an expert in this field.

Also, remember to put attention to the LEDs-per-meter, AFAICR, there are 60 LED/m, 72 LED/m and 144 LED/m models. I used the last one, but as I actually use 1 LED every 2, I'd expect the 72 LED/m to work nicely as well. On the other hand, I'd expect the 60 LED/m one to have a wrong/troublesome LED step. However, this all actually depends on your own keyboard/piano physical keys size.

Hope this helps.
