### ISSUE TITLE
Autosync + Options Persistence missing from Windows pre-compiled version MuseScore_3.0dev_pt0.4.msi

### ISSUE THREAD

**Issue by yba2cuo3** [tomcucinotta/MuseScore#14]
I haven't tried it in Ubuntu yet but Autosync & persistence options don't appear in the piano tutor panel when installing on Windows.

**Comment by tomcucinotta** [comment]
thanks for pointing this out, I need to double-check whether I compiled the Windows binary with the correct commit id. Unfortunately, I'm not a Windows user, so I can recompile on that platform only when I can borrow a Windows laptop from someone, from time to time...

**Comment by tiborkiss** [comment]
I tired to compile in Windows and everything compiles except tutor.cpp and seq.cpp

I used piano-tutor branch.
`
25>textpalette.cpp
25>d:\w\musescore\mscore\tutor.cpp(62): warning C4312: 'type cast': conversion from 'int' to 'HANDLE' of greater size
25>d:\w\musescore\mscore\tutor.cpp(68): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
25>d:\w\musescore\mscore\tutor.cpp(68): error C2146: syntax error: missing ';' before identifier 'WRITE'
25>d:\w\musescore\mscore\tutor.cpp(68): error C2143: syntax error: missing ';' before '{'
25>d:\w\musescore\mscore\tutor.cpp(68): error C2447: '{': missing function header (old-style formal list?)
25>d:\w\musescore\mscore\tutor.cpp(81): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
25>d:\w\musescore\mscore\tutor.cpp(81): error C2086: 'int ssize_t': redefinition
25>d:\w\musescore\mscore\tutor.cpp(68): note: see declaration of 'ssize_t'
25>d:\w\musescore\mscore\tutor.cpp(81): error C2146: syntax error: missing ';' before identifier 'READ'
25>d:\w\musescore\mscore\tutor.cpp(81): error C2143: syntax error: missing ';' before '{'
25>d:\w\musescore\mscore\tutor.cpp(81): error C2447: '{': missing function header (old-style formal list?)
25>d:\w\musescore\mscore\tutor.cpp(97): warning C4311: 'type cast': pointer truncation from 'HANDLE' to 'int'
25>d:\w\musescore\mscore\tutor.cpp(97): warning C4302: 'type cast': truncation from 'HANDLE' to 'int'
25>d:\w\musescore\mscore\tutor.cpp(97): warning C4310: cast truncates constant value
25>d:\w\musescore\mscore\tutor.cpp(107): error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax
25>d:\w\musescore\mscore\tutor.cpp(112): warning C4311: 'type cast': pointer truncation from 'HANDLE' to 'int'
25>d:\w\musescore\mscore\tutor.cpp(112): warning C4302: 'type cast': truncation from 'HANDLE' to 'int'
25>d:\w\musescore\mscore\tutor.cpp(112): warning C4310: cast truncates constant value
25>d:\w\musescore\mscore\tutor.cpp(115): error C2664: 'HANDLE CreateFileW(LPCWSTR,DWORD,DWORD,LPSECURITY_ATTRIBUTES,DWORD,DWORD,HANDLE)': cannot convert argument 1 from 'const _Elem *' to 'LPCWSTR'
25>        with
25>        [
25>            _Elem=char
25>        ]
25>d:\w\musescore\mscore\tutor.cpp(115): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
25>d:\w\musescore\mscore\tutor.cpp(116): warning C4311: 'type cast': pointer truncation from 'HANDLE' to 'int'
25>d:\w\musescore\mscore\tutor.cpp(116): warning C4302: 'type cast': truncation from 'HANDLE' to 'int'
25>d:\w\musescore\mscore\tutor.cpp(116): warning C4310: cast truncates constant value
25>d:\w\musescore\mscore\tutor.cpp(121): warning C4312: 'type cast': conversion from 'int' to 'HANDLE' of greater size
25>d:\w\musescore\mscore\tutor.cpp(126): warning C4312: 'type cast': conversion from 'int' to 'HANDLE' of greater size
25>d:\w\musescore\mscore\tutor.cpp(134): error C3861: 'READ': identifier not found
25>d:\w\musescore\mscore\tutor.cpp(201): error C2065: 'CLOCK_REALTIME': undeclared identifier
25>d:\w\musescore\mscore\tutor.cpp(201): error C3861: 'clock_gettime': identifier not found
25>d:\w\musescore\mscore\tutor.cpp(211): error C3861: 'WRITE': identifier not found
25>d:\w\musescore\mscore\tutor.cpp(216): warning C4311: 'type cast': pointer truncation from 'HANDLE' to 'int'
25>d:\w\musescore\mscore\tutor.cpp(216): warning C4302: 'type cast': truncation from 'HANDLE' to 'int'
25>d:\w\musescore\mscore\tutor.cpp(216): warning C4310: cast truncates constant value
25>d:\w\musescore\mscore\tutor.cpp(309): error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax
25>d:\w\musescore\mscore\tutor.cpp(332): error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax
25>d:\w\musescore\mscore\tutor.cpp(339): error C2065: 'CLOCK_MONOTONIC': undeclared identifier
25>d:\w\musescore\mscore\tutor.cpp(339): error C3861: 'clock_gettime': identifier not found
25>d:\w\musescore\mscore\tutor.cpp(367): error C2065: 'CLOCK_MONOTONIC': undeclared identifier
25>d:\w\musescore\mscore\tutor.cpp(367): error C3861: 'clock_gettime': identifier not found
25>d:\w\musescore\mscore\tutor.cpp(462): warning C4311: 'type cast': pointer truncation from 'HANDLE' to 'int'
25>d:\w\musescore\mscore\tutor.cpp(462): warning C4302: 'type cast': truncation from 'HANDLE' to 'int'
25>d:\w\musescore\mscore\tutor.cpp(462): warning C4310: cast truncates constant value
25>d:\w\musescore\mscore\tutor.cpp(464): warning C4311: 'type cast': pointer truncation from 'HANDLE' to 'int'
25>d:\w\musescore\mscore\tutor.cpp(464): warning C4302: 'type cast': truncation from 'HANDLE' to 'int'
25>d:\w\musescore\mscore\tutor.cpp(464): warning C4310: cast truncates constant value
25>timedialog.cpp
25>d:\w\musescore\mscore\seq.cpp(679): error C2065: 'CLOCK_REALTIME': undeclared identifier
25>d:\w\musescore\mscore\seq.cpp(679): error C3861: 'clock_gettime': identifier not found
25>d:\w\musescore\mscore\seq.cpp(714): error C2065: 'CLOCK_REALTIME': undeclared identifier
25>d:\w\musescore\mscore\seq.cpp(714): error C3861: 'clock_gettime': identifier not found
25>d:\w\musescore\mscore\seq.cpp(1517): error C2065: 'CLOCK_MONOTONIC_RAW': undeclared identifier
25>d:\w\musescore\mscore\seq.cpp(1517): error C3861: 'clock_gettime': identifier not found
25>symboldialog.cpp

....
25>Done building project "mscore.vcxproj" -- FAILED.
========== Build: 24 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

Note that I am not a Windows developer, I work on Ubuntu. I just compiled in someone's laptop and I had no time to fix it. I just would like to use in a small Windows laptop for piano learning. Unfortunately there does not fit a development environment. Eventually next weekend I will borrow my friend's Windows machine which has developer tools.

**Comment by windystrife** [comment]
I tested both Windows and Ubuntu build from https://github.com/tomcucinotta/MuseScore/releases/tag/v3.0dev-pianotutor-0.4
(this one code from 7 Nov 2018, you add Autosync features on 13th Nov 2018)

but it doesn't have Autosync option, can you build the new binaries one from lastest code... Thanks so much

**Comment by tomcucinotta** [comment]
I just rebuilt both binaries (Windows and Linux) with the right commit Id including AutoSync. Please, try it out at:
https://github.com/tomcucinotta/MuseScore/releases/tag/v3.0dev-pianotutor-0.5
and feel free to report any issues you should encounter on the issue tracker.
