### ISSUE TITLE
arduino set up 

### ISSUE THREAD

**Issue by aminesouguir** [tomcucinotta/MuseScore#16]
when i verify the code in Arduino i get an error message:
 Arduino : 1.8.9 (Windows 10), Carte : "Arduino/Genuino Uno"

PianoTutor:30:1: error: stray '\302' in program

 <title>MuseScore/PianoTutor.ino at piano-tutor · tomcucinotta/MuseScore</title>

i don't understand what's wrong with the title line ?

**Comment by tomcucinotta** [comment]
Hi, are you still getting this error ? Did you try with the latest released version ?

Thanks.

**Comment by aminesouguir** [comment]
I solved the issue by copy Past method instead of openinig the .ino file
