### ISSUE TITLE
Arduino not connecting with MuseScore

### ISSUE THREAD

**Issue by konradqwerty** [tomcucinotta/MuseScore#25]
Hi,
My LEDs are not working with MS (Windows). Maybe it has something to do with serial device, but even after changing to ACM1 or number of my COM(5) port.
![image](https://user-images.githubusercontent.com/6072706/70390987-64028480-19d0-11ea-96ca-2834a255342c.png)
Commands through Serial Monitor are working fine, MS discovers my midi device and responds to it (by waiting till I press the correct note). 
When I press Wizard, then also nothing happens. I tried with 2 Arduinos and 2 computers. Newest version installed by .msi, but older bin\ ... .exe also don't seem to work with me (older version can't find my midi device and cmd is showing some warnings).
Every option seems to be changed just like you did, except maybe PortAudio 
![image](https://user-images.githubusercontent.com/6072706/70391414-47b51680-19d5-11ea-8293-8b1b76b4c704.png)
EDIT: I managed to start LEDs on one computer with older version, but then it doesn't see my MIDI device. Other computer, when I open the older version, does see MIDI, but doesn't launch my LEDs (just like the newest version on both computers). 
Debug: Init midi driver failed (C:\...\mscore\pa.cpp:145, virtual bool Ms::Portaudio::init(bool))
EDIT2: I reinstalled midi driver and now it's seen, but I got it working on 1 PC and with older version. It'd be still great to make it working on a laptop with the newest version, as the older one does not save setting (I have to set it up every time). 

Also the bass key is also played as the right hand, left hand is playable only on 2 pianos files.

**Comment by 3Duke** [comment]
Me too, sending "h10202020" from de command windows (Serial Monitor of IDE Arduino) lights the led, but not working from MuseScore, any led lights on (but all other Midi functions are working
By the way, excellent project, this was very similar to my final project of my  engineer studies  some time ago (27 years! all made with ICs , multiplexors, red/green leds...), and now with an Arduino and  a ledstrip it's done !!

**Comment by svanimisetti** [comment]
@3Duke - I am having a similar issue - and followed your recommendations - but still unable to connect to Arduino from MuseScore ( I am using MuseScore3.0dev-PianoTutor0.6 ). From separate serial terminal - there is no issue and Arduino UNO works as expected. Can you provide some instructions on how you got it working?

**Comment by tomcucinotta** [comment]
Closing, please, reopen if needed.
