### ISSUE TITLE
just seen toms you tube of this running on RPI 4, if anybody could give some guidance to install the zip file on a RPI4 that would greatly appreciated, i am obj programmer 6502, 68000 so i dont get this high level stuff and the protocols, just a walk through would be nice i have not done this procedure and i cant find it on You tube so it probably has a name that i just cant think of it, its dead easy in machine code go to the memory location and go, Regards

### ISSUE THREAD

**Issue by Mrroosty** [tomcucinotta/MuseScore#28]

**Comment by tomcucinotta** [comment]
Just download the sources on a RPI4, compile it and install it with the already documented procedure. It will auto-detect it's compiling on a RPI4. The only difference is that you won't need an Arduino, but you have to install the RPI4 library for driving NeoPixel LED stripes, before compiling the MuseScore sources.
