### ISSUE TITLE
Trying to run this code sorry i am a low level programmer and i just dont understand this syntax based stuff can somebody point me in the right direction, regards

### ISSUE THREAD

**Issue by Mrroosty** [tomcucinotta/MuseScore#29]

**Comment by Mrroosty** [comment]
i have  entered the instructions on the git terminal and files load in and compile i think but i dont know how to run it, if anyone has an idea how to do this i would be very greatful for some advice, regards

**Comment by tomcucinotta** [comment]
If you provide more details about what you exactly don't understand from the tutorial, then I can be of some help.
