### ISSUE TITLE
Windows instructions:  download MuseScore-3.0dev-PianoTutor0.1.zip right-click and unzip run the executable found at: bin\MuseScore.exe

### ISSUE THREAD

**Issue by Mrroosty** [tomcucinotta/MuseScore#31]
Windows instructions:

download MuseScore-3.0dev-PianoTutor0.1.zip
right-click and unzip
run the executable found at: bin\MuseScore.exe

**Comment by tomcucinotta** [comment]
Thanks, might be useful for someone.
