### ISSUE TITLE
anybody know where to find this part       miditools/PianoTutor/PianoTutor.ino;

### ISSUE THREAD

**Issue by Mrroosty** [tomcucinotta/MuseScore#33]

**Comment by RobertW62** [comment]
If you havent found it its in the zip file.

**Comment by tomcucinotta** [comment]
Please, make sure you're on the piano-tutor branch of the project.
The file can be found at:
https://github.com/tomcucinotta/MuseScore/blob/piano-tutor/miditools/PianoTutor/PianoTutor.ino
