### ISSUE TITLE
could anybody explain what this step is and how to do it, Step 2b !!!!  regards..................From the Arduino IDE: 2.a) install the Adafruit NeoPixel library, e.g., as explained here; 2.b) open within the above checked out git repository the .ino file: miditools/PianoTutor/PianoTutor.ino;

### ISSUE THREAD

**Issue by Mrroosty** [tomcucinotta/MuseScore#34]

**Comment by pparrilla** [comment]
I don't know if you resolve this issue, but have you change to piano-tutor branch?

**Comment by willi132** [comment]
im also searching for.

**Comment by tomcucinotta** [comment]
It is really all explained in the provided link from the adafruit.com website.

You need to install the Arduino IDE on a PC, here you can find instructions for Linux, Windows and even Mac:
https://support.arduino.cc/hc/en-us/articles/360019833020-Download-and-install-Arduino-IDE

Then, from within the Arduino IDE environment, you need to install the AdaFruit NeoPixel library for driving the LEDs, as explained in the pointer from the tutorial:
https://learn.adafruit.com/adafruit-neopixel-uberguide/arduino-library-installation

Finally, you can use the Arduino IDE to load the PianoTutor.ino file, compile it, and deploy it onto the Arduino board. The .ino file can be found at:
https://github.com/tomcucinotta/MuseScore/blob/piano-tutor/miditools/PianoTutor/PianoTutor.ino

Hope this helps.
