### ISSUE TITLE
Cannot get LEDs to turn on

### ISSUE THREAD

**Issue by TheVicBro** [tomcucinotta/MuseScore#35]
I cannot get the LEDs to turn on. When I play the correct key, it moves on to the next note in MuseScore, but I cannot see any of my LEDs turn on. I am currently on Windows 10 and using the WS2812B LED strips.

**Comment by aGreatDay** [comment]
Make sure the 'Serial Device' is set correct on the 'Setup' tab in the PianoTutorPanel in MuseScore. I'm running on Windows and had to set it to COM3.
